name = "backend"
compatibility_date = "2023-12-01"

[vars]
DATABASE_URL="prisma://accelerate.prisma-data.net/?api_key=eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJhcGlfa2V5IjoiZDIwZTc2ZTMtMzI4Zi00ZDExLWE0YWEtNWMxZmZlYzEzN2ZiIiwidGVuYW50X2lkIjoiMjllYTljYzVhNzE0YWZhZTA2OGI1OGM0ZjEzY2ViNTQ5ZWY4NTcxYThlYTMzODhiYjY5ZmMxMjkwNTk4ZmQyNyIsImludGVybmFsX3NlY3JldCI6IjZjMjM5MmQ3LTQ4ZDEtNDcxZi05MmMyLTFlZDcwN2UzNDc5MiJ9.-Qkdyqaym2iW7Zad0e2z-lkGQeM0LoQxjjz7pVpKfac"
JWT_SECRET = "mediumprismasecrethello"

